# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/heatmap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/heatmap.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16protobuf/heatmap.proto\"|\n\x07Heatmap\x12\x0c\n\x04time\x18\x01 \x01(\r\x12\x0f\n\x07max_lat\x18\x02 \x01(\x02\x12\x10\n\x08max_long\x18\x03 \x01(\x02\x12\x0f\n\x07min_lat\x18\x04 \x01(\x02\x12\x10\n\x08min_long\x18\x05 \x01(\x02\x12\x0c\n\x04size\x18\x06 \x03(\x05\x12\x0f\n\x03map\x18\x07 \x03(\x01\x42\x02\x10\x01\x62\x06proto3')
)




_HEATMAP = _descriptor.Descriptor(
  name='Heatmap',
  full_name='Heatmap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Heatmap.time', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_lat', full_name='Heatmap.max_lat', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_long', full_name='Heatmap.max_long', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_lat', full_name='Heatmap.min_lat', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_long', full_name='Heatmap.min_long', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='Heatmap.size', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='map', full_name='Heatmap.map', index=6,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['Heatmap'] = _HEATMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Heatmap = _reflection.GeneratedProtocolMessageType('Heatmap', (_message.Message,), dict(
  DESCRIPTOR = _HEATMAP,
  __module__ = 'protobuf.heatmap_pb2'
  # @@protoc_insertion_point(class_scope:Heatmap)
  ))
_sym_db.RegisterMessage(Heatmap)


_HEATMAP.fields_by_name['map']._options = None
# @@protoc_insertion_point(module_scope)
